[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
startsecs=3
startretries=10
stopsignal=QUIT
stdout_logfile=/var/log/supervisor/nginx.log
stdout_logfile_maxbytes=0
redirect_stderr=true
